"""initial schema

Revision ID: 4d94150c947c
Revises:
Create Date: 2026-07-13 14:57:54.708690

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4d94150c947c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entities",
        sa.Column("entity_id", sa.String(length=128), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("normalized_name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("entity_id", name=op.f("pk_entities")),
        sa.UniqueConstraint("entity_type", "normalized_name", name=op.f("uq_entities_entity_type")),
    )
    op.create_table(
        "sources",
        sa.Column("source_id", sa.String(length=128), nullable=False),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("imported_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_version", sa.String(length=128), nullable=True),
        sa.Column("original_path_hash", sa.String(length=64), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("source_id", name=op.f("pk_sources")),
    )
    with op.batch_alter_table("sources", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sources_source_type"), ["source_type"], unique=False)

    op.create_table(
        "topics",
        sa.Column("topic_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("topic_id", name=op.f("pk_topics")),
        sa.UniqueConstraint("name", "category", name=op.f("uq_topics_name")),
    )
    op.create_table(
        "events",
        sa.Column("event_id", sa.String(length=128), nullable=False),
        sa.Column("source_id", sa.String(length=128), nullable=False),
        sa.Column("source_record_id", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("timestamp_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("timestamp_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("location_id", sa.String(length=128), nullable=True),
        sa.Column("privacy_level", sa.String(length=16), nullable=False),
        sa.Column("raw_payload_reference", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "privacy_level IN ('private', 'sensitive', 'personal', 'public')",
            name=op.f("ck_events_privacy_level"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.source_id"],
            name=op.f("fk_events_source_id_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_events")),
        sa.UniqueConstraint("source_id", "source_record_id", name=op.f("uq_events_source_id")),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_events_event_type"), ["event_type"], unique=False)
        batch_op.create_index(
            "ix_events_source_type_time",
            ["source_id", "event_type", "timestamp_start"],
            unique=False,
        )
        batch_op.create_index(
            "ix_events_timestamp_range", ["timestamp_start", "timestamp_end"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_events_timestamp_start"), ["timestamp_start"], unique=False
        )

    op.create_table(
        "import_runs",
        sa.Column("import_run_id", sa.String(length=128), nullable=False),
        sa.Column("source_id", sa.String(length=128), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("input_path_hash", sa.String(length=64), nullable=False),
        sa.Column("imported_conversations", sa.Integer(), nullable=False),
        sa.Column("imported_events", sa.Integer(), nullable=False),
        sa.Column("warning_count", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.source_id"],
            name=op.f("fk_import_runs_source_id_sources"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("import_run_id", name=op.f("pk_import_runs")),
    )
    op.create_table(
        "chatgpt_conversations",
        sa.Column("conversation_id", sa.String(length=255), nullable=False),
        sa.Column("source_id", sa.String(length=128), nullable=False),
        sa.Column("event_id", sa.String(length=128), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("message_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.event_id"],
            name=op.f("fk_chatgpt_conversations_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.source_id"],
            name=op.f("fk_chatgpt_conversations_source_id_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("conversation_id", name=op.f("pk_chatgpt_conversations")),
        sa.UniqueConstraint("event_id", name=op.f("uq_chatgpt_conversations_event_id")),
    )
    with op.batch_alter_table("chatgpt_conversations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_chatgpt_conversations_created_at"), ["created_at"], unique=False
        )

    op.create_table(
        "event_entities",
        sa.Column("event_id", sa.String(length=128), nullable=False),
        sa.Column("entity_id", sa.String(length=128), nullable=False),
        sa.Column("relation_type", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.entity_id"],
            name=op.f("fk_event_entities_entity_id_entities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.event_id"],
            name=op.f("fk_event_entities_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "event_id", "entity_id", "relation_type", name=op.f("pk_event_entities")
        ),
    )
    op.create_table(
        "event_relations",
        sa.Column("relation_id", sa.String(length=128), nullable=False),
        sa.Column("source_event_id", sa.String(length=128), nullable=False),
        sa.Column("target_event_id", sa.String(length=128), nullable=False),
        sa.Column("relation_type", sa.String(length=64), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_event_id"],
            ["events.event_id"],
            name=op.f("fk_event_relations_source_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_event_id"],
            ["events.event_id"],
            name=op.f("fk_event_relations_target_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("relation_id", name=op.f("pk_event_relations")),
        sa.UniqueConstraint(
            "source_event_id",
            "target_event_id",
            "relation_type",
            name=op.f("uq_event_relations_source_event_id"),
        ),
    )
    op.create_table(
        "event_topics",
        sa.Column("event_id", sa.String(length=128), nullable=False),
        sa.Column("topic_id", sa.String(length=128), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.event_id"],
            name=op.f("fk_event_topics_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.topic_id"],
            name=op.f("fk_event_topics_topic_id_topics"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("event_id", "topic_id", name=op.f("pk_event_topics")),
    )
    op.create_table(
        "chatgpt_messages",
        sa.Column("message_key", sa.String(length=128), nullable=False),
        sa.Column("message_id", sa.String(length=255), nullable=False),
        sa.Column("conversation_id", sa.String(length=255), nullable=False),
        sa.Column("event_id", sa.String(length=128), nullable=False),
        sa.Column("parent_message_key", sa.String(length=128), nullable=True),
        sa.Column("parent_message_id", sa.String(length=255), nullable=True),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("content_type", sa.String(length=64), nullable=False),
        sa.Column("is_on_current_branch", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["chatgpt_conversations.conversation_id"],
            name=op.f("fk_chatgpt_messages_conversation_id_chatgpt_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.event_id"],
            name=op.f("fk_chatgpt_messages_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_message_key"],
            ["chatgpt_messages.message_key"],
            name=op.f("fk_chatgpt_messages_parent_message_key_chatgpt_messages"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("message_key", name=op.f("pk_chatgpt_messages")),
        sa.UniqueConstraint(
            "conversation_id",
            "message_id",
            name="uq_chatgpt_messages_conversation_message",
        ),
        sa.UniqueConstraint(
            "conversation_id",
            "sequence_number",
            name="uq_chatgpt_messages_conversation_sequence",
        ),
        sa.UniqueConstraint("event_id", name=op.f("uq_chatgpt_messages_event_id")),
    )
    with op.batch_alter_table("chatgpt_messages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_chatgpt_messages_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_chatgpt_messages_message_id"), ["message_id"], unique=False
        )

    op.execute(
        "CREATE VIRTUAL TABLE events_fts USING fts5("
        "title, text, content='events', content_rowid='rowid')"
    )
    op.execute(
        "CREATE TRIGGER events_fts_insert AFTER INSERT ON events BEGIN "
        "INSERT INTO events_fts(rowid, title, text) VALUES (new.rowid, new.title, new.text); END"
    )
    op.execute(
        "CREATE TRIGGER events_fts_delete AFTER DELETE ON events BEGIN "
        "INSERT INTO events_fts(events_fts, rowid, title, text) "
        "VALUES ('delete', old.rowid, old.title, old.text); END"
    )
    op.execute(
        "CREATE TRIGGER events_fts_update AFTER UPDATE OF title, text ON events BEGIN "
        "INSERT INTO events_fts(events_fts, rowid, title, text) "
        "VALUES ('delete', old.rowid, old.title, old.text); "
        "INSERT INTO events_fts(rowid, title, text) VALUES (new.rowid, new.title, new.text); END"
    )
    op.execute("INSERT INTO events_fts(rowid, title, text) SELECT rowid, title, text FROM events")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS events_fts_update")
    op.execute("DROP TRIGGER IF EXISTS events_fts_delete")
    op.execute("DROP TRIGGER IF EXISTS events_fts_insert")
    op.execute("DROP TABLE IF EXISTS events_fts")

    with op.batch_alter_table("chatgpt_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chatgpt_messages_message_id"))
        batch_op.drop_index(batch_op.f("ix_chatgpt_messages_created_at"))

    op.drop_table("chatgpt_messages")
    op.drop_table("event_topics")
    op.drop_table("event_relations")
    op.drop_table("event_entities")
    with op.batch_alter_table("chatgpt_conversations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chatgpt_conversations_created_at"))

    op.drop_table("chatgpt_conversations")
    op.drop_table("import_runs")
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_timestamp_start"))
        batch_op.drop_index("ix_events_timestamp_range")
        batch_op.drop_index("ix_events_source_type_time")
        batch_op.drop_index(batch_op.f("ix_events_event_type"))

    op.drop_table("events")
    op.drop_table("topics")
    with op.batch_alter_table("sources", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sources_source_type"))

    op.drop_table("sources")
    op.drop_table("entities")
    # ### end Alembic commands ###
