"""separate candidate terms from topics

Revision ID: 703c9442f139
Revises: f9a405ee6284
Create Date: 2026-07-14 07:06:23.450968

"""

import hashlib
import unicodedata
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "703c9442f139"
down_revision: Union[str, Sequence[str], None] = "f9a405ee6284"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candidate_terms",
        sa.Column("term_id", sa.String(length=128), nullable=False),
        sa.Column("term", sa.Text(), nullable=False),
        sa.Column("normalized_term", sa.Text(), nullable=False),
        sa.Column("ngram_size", sa.Integer(), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=True),
        sa.Column("message_count", sa.Integer(), nullable=False),
        sa.Column("context_count", sa.Integer(), nullable=False),
        sa.Column("document_frequency", sa.Integer(), nullable=False),
        sa.Column("tfidf_score", sa.Float(), nullable=False),
        sa.Column("quality_score", sa.Float(), nullable=False),
        sa.Column("quality_status", sa.String(length=32), nullable=False),
        sa.Column("rejection_reason", sa.String(length=64), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "quality_status IN ('accepted', 'rejected', 'legacy')",
            name=op.f("ck_candidate_terms_candidate_quality_status"),
        ),
        sa.CheckConstraint(
            "ngram_size >= 1 AND ngram_size <= 3",
            name=op.f("ck_candidate_terms_candidate_ngram_size"),
        ),
        sa.PrimaryKeyConstraint("term_id", name=op.f("pk_candidate_terms")),
        sa.UniqueConstraint("normalized_term", name=op.f("uq_candidate_terms_normalized_term")),
    )
    with op.batch_alter_table("candidate_terms", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_candidate_terms_is_active"), ["is_active"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_candidate_terms_language"), ["language"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_candidate_terms_quality_status"), ["quality_status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_candidate_terms_rejection_reason"), ["rejection_reason"], unique=False
        )

    op.create_table(
        "topic_terms",
        sa.Column("topic_id", sa.String(length=128), nullable=False),
        sa.Column("term_id", sa.String(length=128), nullable=False),
        sa.Column("relation_type", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "relation_type IN ('primary', 'alias', 'manual')",
            name=op.f("ck_topic_terms_topic_term_relation_type"),
        ),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["candidate_terms.term_id"],
            name=op.f("fk_topic_terms_term_id_candidate_terms"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.topic_id"],
            name=op.f("fk_topic_terms_topic_id_topics"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("topic_id", "term_id", name=op.f("pk_topic_terms")),
    )
    op.create_table(
        "event_candidate_terms",
        sa.Column("event_id", sa.String(length=128), nullable=False),
        sa.Column("term_id", sa.String(length=128), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.event_id"],
            name=op.f("fk_event_candidate_terms_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["candidate_terms.term_id"],
            name=op.f("fk_event_candidate_terms_term_id_candidate_terms"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("event_id", "term_id", name=op.f("pk_event_candidate_terms")),
    )
    with op.batch_alter_table("topics", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("status", sa.String(length=32), server_default="active", nullable=False)
        )
        batch_op.add_column(
            sa.Column("origin", sa.String(length=32), server_default="automatic", nullable=False)
        )
        batch_op.add_column(
            sa.Column("is_active", sa.Boolean(), server_default="1", nullable=False)
        )
        batch_op.create_index(batch_op.f("ix_topics_is_active"), ["is_active"], unique=False)
        batch_op.create_index(batch_op.f("ix_topics_status"), ["status"], unique=False)

    connection = op.get_bind()
    legacy_topics = connection.execute(
        sa.text(
            "SELECT topic_id, name, message_count, conversation_count FROM topics ORDER BY topic_id"
        )
    ).mappings()
    term_ids_by_topic: dict[str, str] = {}
    candidate_rows_by_id: dict[str, dict[str, object]] = {}
    topic_term_rows = []
    for topic in legacy_topics:
        normalized = " ".join(unicodedata.normalize("NFKC", topic["name"]).casefold().split())
        term_id = f"term-{hashlib.sha256(normalized.encode()).hexdigest()}"
        term_ids_by_topic[topic["topic_id"]] = term_id
        candidate_rows_by_id.setdefault(
            term_id,
            {
                "term_id": term_id,
                "term": topic["name"],
                "normalized_term": normalized,
                "ngram_size": min(3, normalized.count(" ") + 1),
                "message_count": topic["message_count"],
                "context_count": topic["conversation_count"],
                "document_frequency": topic["message_count"],
            },
        )
        topic_term_rows.append(
            {"topic_id": topic["topic_id"], "term_id": term_id, "relation_type": "primary"}
        )
    if candidate_rows_by_id:
        connection.execute(
            sa.text(
                "INSERT INTO candidate_terms "
                "(term_id, term, normalized_term, ngram_size, language, message_count, "
                "context_count, document_frequency, tfidf_score, quality_score, "
                "quality_status, rejection_reason, is_active) VALUES "
                "(:term_id, :term, :normalized_term, :ngram_size, NULL, :message_count, "
                ":context_count, :document_frequency, 0.0, 0.0, 'legacy', NULL, 1)"
            ),
            list(candidate_rows_by_id.values()),
        )
        connection.execute(
            sa.text(
                "INSERT INTO topic_terms (topic_id, term_id, relation_type) "
                "VALUES (:topic_id, :term_id, :relation_type)"
            ),
            topic_term_rows,
        )
        event_rows = connection.execute(
            sa.text("SELECT event_id, topic_id, weight FROM event_topics")
        ).mappings()
        legacy_event_terms: dict[tuple[str, str], float] = {}
        for row in event_rows:
            key = (row["event_id"], term_ids_by_topic[row["topic_id"]])
            legacy_event_terms[key] = max(legacy_event_terms.get(key, 0.0), row["weight"])
        connection.execute(
            sa.text(
                "INSERT INTO event_candidate_terms (event_id, term_id, weight) "
                "VALUES (:event_id, :term_id, :weight)"
            ),
            [
                {
                    "event_id": event_id,
                    "term_id": term_id,
                    "weight": weight,
                }
                for (event_id, term_id), weight in legacy_event_terms.items()
            ],
        )
        connection.execute(sa.text("UPDATE topics SET origin = 'legacy'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("topics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_topics_status"))
        batch_op.drop_index(batch_op.f("ix_topics_is_active"))
        batch_op.drop_column("is_active")
        batch_op.drop_column("origin")
        batch_op.drop_column("status")

    op.drop_table("event_candidate_terms")
    op.drop_table("topic_terms")
    with op.batch_alter_table("candidate_terms", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_candidate_terms_rejection_reason"))
        batch_op.drop_index(batch_op.f("ix_candidate_terms_quality_status"))
        batch_op.drop_index(batch_op.f("ix_candidate_terms_language"))
        batch_op.drop_index(batch_op.f("ix_candidate_terms_is_active"))

    op.drop_table("candidate_terms")
    # ### end Alembic commands ###
