"""add topic graph and event activity

Revision ID: f9a405ee6284
Revises: 4d94150c947c
Create Date: 2026-07-13 19:18:57.741444

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f9a405ee6284"
down_revision: Union[str, Sequence[str], None] = "4d94150c947c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "topic_relations",
        sa.Column("relation_id", sa.String(length=128), nullable=False),
        sa.Column("source_topic_id", sa.String(length=128), nullable=False),
        sa.Column("target_topic_id", sa.String(length=128), nullable=False),
        sa.Column("message_count", sa.Integer(), nullable=False),
        sa.Column("conversation_count", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_topic_id"],
            ["topics.topic_id"],
            name=op.f("fk_topic_relations_source_topic_id_topics"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_topic_id"],
            ["topics.topic_id"],
            name=op.f("fk_topic_relations_target_topic_id_topics"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("relation_id", name=op.f("pk_topic_relations")),
        sa.UniqueConstraint(
            "source_topic_id", "target_topic_id", name=op.f("uq_topic_relations_source_topic_id")
        ),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("context_id", sa.String(length=255), nullable=True))
        batch_op.add_column(
            sa.Column("is_active", sa.Boolean(), server_default="1", nullable=False)
        )
        batch_op.add_column(
            sa.Column("analysis_enabled", sa.Boolean(), server_default="1", nullable=False)
        )
        batch_op.create_index(
            batch_op.f("ix_events_analysis_enabled"), ["analysis_enabled"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_events_context_id"), ["context_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_is_active"), ["is_active"], unique=False)

    with op.batch_alter_table("topics", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("message_count", sa.Integer(), server_default="0", nullable=False)
        )
        batch_op.add_column(
            sa.Column("conversation_count", sa.Integer(), server_default="0", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("topics", schema=None) as batch_op:
        batch_op.drop_column("conversation_count")
        batch_op.drop_column("message_count")

    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_analysis_enabled"))
        batch_op.drop_index(batch_op.f("ix_events_context_id"))
        batch_op.drop_index(batch_op.f("ix_events_is_active"))
        batch_op.drop_column("analysis_enabled")
        batch_op.drop_column("is_active")
        batch_op.drop_column("context_id")

    op.drop_table("topic_relations")
    # ### end Alembic commands ###
